<a href="https://colab.research.google.com/github/rjsdn2308/medical.data/blob/main/03_intro_variants_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 활용 데이터 처리
## 데이터 불러오기
- EBI에서 제공하는 유전자 변이 데이터 다운로드
  - https://www.ebi.ac.uk/gwas/variants/rs7329174

- 구글 드라이브에 해당 파일 업로드(다운로드 파일 이름에서 날짜는 삭제)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
# 주어진 경로에서 tsv파일을 읽어 dataframe으로 로드
df = pd.read_csv('/content/drive/MyDrive/2025-1/md/gwas-association-downloaded_rsId_rs7329174.tsv', sep="\t", encoding = "utf-8")
df.head() # 기본적으로 5개의 행을 출력합니다.
# v파일이 탭으로 구분된 값이므로 separator를 탭(|t)으로 지정
# 인코딩 방식은 UTP-8로 지정

DATE ADDED TO CATALOG  PUBMEDID FIRST AUTHOR        DATE  \
0            2013-02-21  23273568       Yang W  2012-12-27   
1            2017-02-19  27399966    Morris DL  2016-07-11   
2            2011-01-03  21044949       Yang J  2010-11-02   
3            2013-02-27  23266558   Yamazaki K  2012-12-21   
4            2021-10-20  34076728     Zhang YM  2021-06-02   

              JOURNAL                                  LINK  \
0      Am J Hum Genet  www.ncbi.nlm.nih.gov/pubmed/23273568   
1           Nat Genet  www.ncbi.nlm.nih.gov/pubmed/27399966   
2       Hum Mol Genet  www.ncbi.nlm.nih.gov/pubmed/21044949   
3    Gastroenterology  www.ncbi.nlm.nih.gov/pubmed/23266558   
4  Mol Genet Genomics  www.ncbi.nlm.nih.gov/pubmed/34076728   

                                               STUDY  \
0  Meta-analysis followed by replication identifi...   
1  Genome-wide association meta-analysis in Chine...   
2  ELF1 is associated with systemic lupus erythem...   
3  A genome-wide association study identifies 2 s...   
4  Shared genetic study gives insights into the s...   

                  DISEASE/TRAIT  \
0  Systemic lupus erythematosus   
1  Systemic lupus erythematosus   
2  Systemic lupus erythematosus   
3               Crohn's disease   
4  Systemic lupus erythematosus   

                                 INITIAL SAMPLE SIZE  \
0  1,656 Han Chinese ancestry cases, 3,394 Han Ch...   
1  1,659 Chinese ancestry cases, 3,398 Chinese an...   
2  612 Chinese ancestry cases, 1,160 Chinese ance...   
3  372 Japanese ancestry cases,3,389 Japanese anc...   
4  1,639 East Asian ancestry cases, 2,410 East As...   

                             REPLICATION SAMPLE SIZE  ... PVALUE_MLOG  \
0  3,256 Han Chinese ancestry cases, 5,667 Han Ch...  ...    5.221849   
1  3,043 Chinese ancestry cases, 5,074 Chinese an...  ...    5.522879   
2  2,090 Chinese ancestry cases, 1,981 Chinese an...  ...    8.000000   
3  Up to 1,151 Japanese ancestry cases, up to 15,...  ...    8.096910   
4                                                NaN  ...    5.522879   

   P-VALUE (TEXT)  OR or BETA 95% CI (TEXT)    PLATFORM [SNPS PASSING QC]  \
0             NaN        1.45           NaN  Illumina [2100739] (imputed)   
1       (Chinese)        1.27          [NR]        NR [6344733] (imputed)   
2             NaN        1.26   [1.16-1.36]             Illumina [513108]   
3             NaN        1.27   [1.17-1.38]  Illumina [4929034] (imputed)   
4             NaN         NaN           NaN       Illumina [NR] (imputed)   

   CNV                  MAPPED_TRAIT  \
0    N  systemic lupus erythematosus   
1    N  systemic lupus erythematosus   
2    N  systemic lupus erythematosus   
3    N               Crohn's disease   
4    N  systemic lupus erythematosus   

                               MAPPED_TRAIT_URI  STUDY ACCESSION  \
0  http://purl.obolibrary.org/obo/MONDO_0007915       GCST001795   
1  http://purl.obolibrary.org/obo/MONDO_0007915       GCST003622   
2  http://purl.obolibrary.org/obo/MONDO_0007915       GCST000858   
3          http://www.ebi.ac.uk/efo/EFO_0000384       GCST001785   
4  http://purl.obolibrary.org/obo/MONDO_0007915     GCST90020042   

          GENOTYPING TECHNOLOGY  
0  Genome-wide genotyping array  
1  Genome-wide genotyping array  
2  Genome-wide genotyping array  
3  Genome-wide genotyping array  
4  Genome-wide genotyping array  

[5 rows x 38 columns]

## 데이터프레임 전처리
- 결측값 처리
- 원핫인코딩

In [ ]:
df.shape

(6, 38)

In [ ]:
df_fixed = df # df를 df_fixed에 복사하여, df_fixed는 df와 동일한 데이터를 가리킵니다.
df_fixed['P-VALUE (TEXT)'] = df_fixed['P-VALUE (TEXT)'].fillna('0')
# df_fixed['b'] = df_fixed['b'].fillna(df_fixed.mean()['a'])

df_fixed.head()

DATE ADDED TO CATALOG  PUBMEDID FIRST AUTHOR        DATE  \
0            2013-02-21  23273568       Yang W  2012-12-27   
1            2017-02-19  27399966    Morris DL  2016-07-11   
2            2011-01-03  21044949       Yang J  2010-11-02   
3            2013-02-27  23266558   Yamazaki K  2012-12-21   
4            2021-10-20  34076728     Zhang YM  2021-06-02   

              JOURNAL                                  LINK  \
0      Am J Hum Genet  www.ncbi.nlm.nih.gov/pubmed/23273568   
1           Nat Genet  www.ncbi.nlm.nih.gov/pubmed/27399966   
2       Hum Mol Genet  www.ncbi.nlm.nih.gov/pubmed/21044949   
3    Gastroenterology  www.ncbi.nlm.nih.gov/pubmed/23266558   
4  Mol Genet Genomics  www.ncbi.nlm.nih.gov/pubmed/34076728   

                                               STUDY  \
0  Meta-analysis followed by replication identifi...   
1  Genome-wide association meta-analysis in Chine...   
2  ELF1 is associated with systemic lupus erythem...   
3  A genome-wide association study identifies 2 s...   
4  Shared genetic study gives insights into the s...   

                  DISEASE/TRAIT  \
0  Systemic lupus erythematosus   
1  Systemic lupus erythematosus   
2  Systemic lupus erythematosus   
3               Crohn's disease   
4  Systemic lupus erythematosus   

                                 INITIAL SAMPLE SIZE  \
0  1,656 Han Chinese ancestry cases, 3,394 Han Ch...   
1  1,659 Chinese ancestry cases, 3,398 Chinese an...   
2  612 Chinese ancestry cases, 1,160 Chinese ance...   
3  372 Japanese ancestry cases,3,389 Japanese anc...   
4  1,639 East Asian ancestry cases, 2,410 East As...   

                             REPLICATION SAMPLE SIZE  ... PVALUE_MLOG  \
0  3,256 Han Chinese ancestry cases, 5,667 Han Ch...  ...    5.221849   
1  3,043 Chinese ancestry cases, 5,074 Chinese an...  ...    5.522879   
2  2,090 Chinese ancestry cases, 1,981 Chinese an...  ...    8.000000   
3  Up to 1,151 Japanese ancestry cases, up to 15,...  ...    8.096910   
4                                                NaN  ...    5.522879   

   P-VALUE (TEXT)  OR or BETA 95% CI (TEXT)    PLATFORM [SNPS PASSING QC]  \
0               0        1.45           NaN  Illumina [2100739] (imputed)   
1       (Chinese)        1.27          [NR]        NR [6344733] (imputed)   
2               0        1.26   [1.16-1.36]             Illumina [513108]   
3               0        1.27   [1.17-1.38]  Illumina [4929034] (imputed)   
4               0         NaN           NaN       Illumina [NR] (imputed)   

   CNV                  MAPPED_TRAIT  \
0    N  systemic lupus erythematosus   
1    N  systemic lupus erythematosus   
2    N  systemic lupus erythematosus   
3    N               Crohn's disease   
4    N  systemic lupus erythematosus   

                               MAPPED_TRAIT_URI  STUDY ACCESSION  \
0  http://purl.obolibrary.org/obo/MONDO_0007915       GCST001795   
1  http://purl.obolibrary.org/obo/MONDO_0007915       GCST003622   
2  http://purl.obolibrary.org/obo/MONDO_0007915       GCST000858   
3          http://www.ebi.ac.uk/efo/EFO_0000384       GCST001785   
4  http://purl.obolibrary.org/obo/MONDO_0007915     GCST90020042   

          GENOTYPING TECHNOLOGY  
0  Genome-wide genotyping array  
1  Genome-wide genotyping array  
2  Genome-wide genotyping array  
3  Genome-wide genotyping array  
4  Genome-wide genotyping array  

[5 rows x 38 columns]

In [ ]:
df_fixed2 = df
df_fixed2 = df_fixed2.fillna(0)
df_fixed2.head()

DATE ADDED TO CATALOG  PUBMEDID FIRST AUTHOR        DATE  \
0            2013-02-21  23273568       Yang W  2012-12-27   
1            2017-02-19  27399966    Morris DL  2016-07-11   
2            2011-01-03  21044949       Yang J  2010-11-02   
3            2013-02-27  23266558   Yamazaki K  2012-12-21   
4            2021-10-20  34076728     Zhang YM  2021-06-02   

              JOURNAL                                  LINK  \
0      Am J Hum Genet  www.ncbi.nlm.nih.gov/pubmed/23273568   
1           Nat Genet  www.ncbi.nlm.nih.gov/pubmed/27399966   
2       Hum Mol Genet  www.ncbi.nlm.nih.gov/pubmed/21044949   
3    Gastroenterology  www.ncbi.nlm.nih.gov/pubmed/23266558   
4  Mol Genet Genomics  www.ncbi.nlm.nih.gov/pubmed/34076728   

                                               STUDY  \
0  Meta-analysis followed by replication identifi...   
1  Genome-wide association meta-analysis in Chine...   
2  ELF1 is associated with systemic lupus erythem...   
3  A genome-wide association study identifies 2 s...   
4  Shared genetic study gives insights into the s...   

                  DISEASE/TRAIT  \
0  Systemic lupus erythematosus   
1  Systemic lupus erythematosus   
2  Systemic lupus erythematosus   
3               Crohn's disease   
4  Systemic lupus erythematosus   

                                 INITIAL SAMPLE SIZE  \
0  1,656 Han Chinese ancestry cases, 3,394 Han Ch...   
1  1,659 Chinese ancestry cases, 3,398 Chinese an...   
2  612 Chinese ancestry cases, 1,160 Chinese ance...   
3  372 Japanese ancestry cases,3,389 Japanese anc...   
4  1,639 East Asian ancestry cases, 2,410 East As...   

                             REPLICATION SAMPLE SIZE  ... PVALUE_MLOG  \
0  3,256 Han Chinese ancestry cases, 5,667 Han Ch...  ...    5.221849   
1  3,043 Chinese ancestry cases, 5,074 Chinese an...  ...    5.522879   
2  2,090 Chinese ancestry cases, 1,981 Chinese an...  ...    8.000000   
3  Up to 1,151 Japanese ancestry cases, up to 15,...  ...    8.096910   
4                                                  0  ...    5.522879   

   P-VALUE (TEXT)  OR or BETA 95% CI (TEXT)    PLATFORM [SNPS PASSING QC]  \
0               0        1.45             0  Illumina [2100739] (imputed)   
1       (Chinese)        1.27          [NR]        NR [6344733] (imputed)   
2               0        1.26   [1.16-1.36]             Illumina [513108]   
3               0        1.27   [1.17-1.38]  Illumina [4929034] (imputed)   
4               0        0.00             0       Illumina [NR] (imputed)   

   CNV                  MAPPED_TRAIT  \
0    N  systemic lupus erythematosus   
1    N  systemic lupus erythematosus   
2    N  systemic lupus erythematosus   
3    N               Crohn's disease   
4    N  systemic lupus erythematosus   

                               MAPPED_TRAIT_URI  STUDY ACCESSION  \
0  http://purl.obolibrary.org/obo/MONDO_0007915       GCST001795   
1  http://purl.obolibrary.org/obo/MONDO_0007915       GCST003622   
2  http://purl.obolibrary.org/obo/MONDO_0007915       GCST000858   
3          http://www.ebi.ac.uk/efo/EFO_0000384       GCST001785   
4  http://purl.obolibrary.org/obo/MONDO_0007915     GCST90020042   

          GENOTYPING TECHNOLOGY  
0  Genome-wide genotyping array  
1  Genome-wide genotyping array  
2  Genome-wide genotyping array  
3  Genome-wide genotyping array  
4  Genome-wide genotyping array  

[5 rows x 38 columns]

In [ ]:
df_fixed2['OR or BETA']

0    1.4500
1    1.2700
2    1.2600
3    1.2700
4    0.0000
5    0.0211
Name: OR or BETA, dtype: float64

In [ ]:
df_fixed2.rename(columns={'OR or BETA':'OR'}, inplace=True)
# df_fixed2['OR or BETA'] error!
df_fixed2['OR']

0    1.4500
1    1.2700
2    1.2600
3    1.2700
4    0.0000
5    0.0211
Name: OR, dtype: float64

In [ ]:
#df.columns
pvalue = df_fixed2['P-VALUE']
pvalue

0    6.000000e-06
1    3.000000e-06
2    1.000000e-08
3    8.000000e-09
4    3.000000e-06
5    8.000000e-26
Name: P-VALUE, dtype: float64

In [ ]:
df_fixed2['DISEASE/TRAIT']

0    Systemic lupus erythematosus
1    Systemic lupus erythematosus
2    Systemic lupus erythematosus
3                 Crohn's disease
4    Systemic lupus erythematosus
5                          Height
Name: DISEASE/TRAIT, dtype: object

In [ ]:
trait = pd.get_dummies(df_fixed2['DISEASE/TRAIT'])
trait

Crohn's disease  Height  Systemic lupus erythematosus
0            False   False                          True
1            False   False                          True
2            False   False                          True
3             True   False                         False
4            False   False                          True
5            False    True                         False

In [ ]:
trait = pd.get_dummies(df_fixed2['DISEASE/TRAIT'],dtype=int)
trait

Crohn's disease  Height  Systemic lupus erythematosus
0                0       0                             1
1                0       0                             1
2                0       0                             1
3                1       0                             0
4                0       0                             1
5                0       1                             0

# Numpy 다차원 배열 변환

In [ ]:
assoc = pd.concat([trait, pvalue, df_fixed2['OR']], axis=1) # 왼->오 방향
assoc

Crohn's disease  Height  Systemic lupus erythematosus       P-VALUE      OR
0                0       0                             1  6.000000e-06  1.4500
1                0       0                             1  3.000000e-06  1.2700
2                0       0                             1  1.000000e-08  1.2600
3                1       0                             0  8.000000e-09  1.2700
4                0       0                             1  3.000000e-06  0.0000
5                0       1                             0  8.000000e-26  0.0211

In [ ]:
import numpy as np
assoc_np = np.array(assoc)
assoc_np

array([[0.00e+00, 0.00e+00, 1.00e+00, 6.00e-06, 1.45e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.00e-06, 1.27e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.00e-08, 1.26e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 8.00e-09, 1.27e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.00e-06, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 8.00e-26, 2.11e-02]])

## Numpy broadcasting

In [ ]:
assoc_np * 0 + 3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
assoc_np_bc = assoc_np * 0 +3
assoc_np + assoc_np_bc

array([[3.        , 3.        , 4.        , 3.000006  , 4.45      ],
       [3.        , 3.        , 4.        , 3.000003  , 4.27      ],
       [3.        , 3.        , 4.        , 3.00000001, 4.26      ],
       [4.        , 3.        , 3.        , 3.00000001, 4.27      ],
       [3.        , 3.        , 4.        , 3.000003  , 3.        ],
       [3.        , 4.        , 3.        , 3.        , 3.0211    ]])

In [ ]:
sample = [5, 5, 5, 5, 5]
sample_bc = assoc_np * 0 + 3
sample + sample_bc

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

## List to Numpy Array

In [ ]:
test = np.array([[1,2,3], [4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

## Reshape

In [ ]:
test4by4 = np.array(list(range(16))).reshape((4,4))
test4by4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Fill 0 or 1

In [ ]:
test = np.ones_like(test4by4)
test

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
test = np.ones(16)
test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
test = np.zeros((2,5))
test

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
test4by4[1,0]

np.int64(4)

## Slicing

In [ ]:
test4by4[2]

array([ 8,  9, 10, 11])

In [ ]:
test4by4[2,:]

array([ 8,  9, 10, 11])

In [ ]:
test4by4[:,2]

array([ 2,  6, 10, 14])

In [ ]:
test4by4[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
test4by4[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
test4by4[test4by4[:,0]<5]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Mean

In [ ]:
target = np.ones((10000,100))
target.shape

(10000, 100)

In [ ]:
mean = target.mean(axis=1)
mean.shape

(10000,)

In [ ]:
mean

array([1., 1., 1., ..., 1., 1., 1.])

# Image 배열

In [ ]:
images = np.random.uniform(low=0, high=1, size=(1000, 400, 300, 3)) # 400x300 이미지 1000장
images.shape

In [ ]:
img = images[0]
img.shape

In [ ]:
img

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(img)